### ISSUE TITLE
Static contructors do not work properly for non-primitive data types and Arrays

### ISSUE THREAD

**Issue by lt72** [NETMF/llilum#17]
The LLVM code generator does not correctly allocate space for types that need initialization. Types are correctly dumped among the globals, but we do make no space for initialization value.

**Comment by ckarenz** [comment]
This appears to be a bug in LLVM code generation.  Static readonly arrays of primitives generate array data in the .text section and a placeholder object in .data which will be copied to when static constructors are run.  Since the second object is always overwritten, we initialize it with zero data per the CLR spec.

In LLVM, all-zero arrays get replaced with ConstAggregateZero.  However, when this happens the size information of the array is lost (sidenote: size information is retained when using UndefValue instead).  This is outside our control, but we can work around this temporarily by inserting one non-zero element into the array.

This may just be an issue with LLVM 3.5.  If the issue still presents in 3.6.1, we'll ultimately have to address the root cause there.  In the meantime, we can use the above workaround.
