### ISSUE TITLE
 What is the difference between  LlilumOSAbstraction and LlilumCMSIS-RTOS ？？

### ISSUE THREAD

**Issue by snikeguo** [NETMF/llilum#232]
![qq 20160904012710](https://cloud.githubusercontent.com/assets/20830435/18226546/baea3e9c-723e-11e6-8eaa-a0c2bf871ac5.jpg)

LlilumOSAbstraction is  RTOS ‘s HAL??

LlilumOSAbstraction   contains LlilumCMSIS-RTOS ?

**Comment by lt72** [comment]
The CMSIS-RTOS library implements the ARM CMSIS-RTOS standard, which is an attempt by ARM to standardize a RTOS interface for their Cortex-M MCUs. You find more info and pointers to ARM docs here: 
https://github.com/NETMF/llilum/tree/dev/Zelig/Zelig/RunTime/Zelig/LlilumCMSIS-RTOS 

LLILUM implements and exports the CMSIS-RTOS standard, so that libraries written against that standard can seamlessly work. An example of that (the only one in LLILUM) is the port for the lwIP stack.

The OS Abstraction library is instead the LLILUM abstraction of the RTOS and I/O related function that need implementation for the I/O libraries and the scheduler to work on a given processor. 
Note that LLILUM needs no RTOS to work, and therefore the scheduler and threading abstractions are only implemented for the Win32 case.
All I/O instead actually goes through the abstractions (e.g. GPIO) and it is implemented on mBed.
