### ISSUE TITLE
Q: Customized startup_xxx.s files?

### ISSUE THREAD

**Issue by cw2** [NETMF/llilum#68]
I noticed CUSTOM_STUB_GetHeapSize() function uses __HeapEnd ~~and __HeapBase~~ variable which are defined in Llilum startup_xxx.s files, but not in their original mbed versions - so I assume those files have been edited (?)

Are there any other important modifications of the mbed sources? (I don't mean physical file differences, those can be easily compared, but high-level "don't forget to do this while adding support for xxx" things that are not [yet] documented...)

_Edit: Corrected __HeapBase reference, which is defined in mbed._

**Comment by ZachNL** [comment]
Yes, the startup_xxx.s files have been changed so that the Llilum heap size can be dynamically calculated.  It was previously defined in the startup_xxx.s file and inside managed code.  This change removes that duplication.  

As far as other differences between original mbed code, I don't personally know of any other major modifications or assumptions that we make regarding mbed.

**Comment by cw2** [comment]
Ok, thanks for the clarification.
