### ISSUE TITLE
Llvm.NET.NativeModule does not print context when reporting errors.

### ISSUE THREAD

**Issue by ckarenz** [NETMF/llilum#74]
The following method returns only the error, but not the text representation when it encounters malformed LLVM code:

```
    public string AsString( )
    {
        string errMsg;
        if( !Verify( out errMsg ) )
            return $"Invalid Module: {errMsg}";

        return NativeMethods.MarshalMsg( NativeMethods.PrintModuleToString( ModuleHandle ) );
    }
```

This prevents analysis of the error without disabling the early return.  We need to ensure that we still dump the text representation with PrintModuleToString even in the event of an error.

The command line tools will print the same error, so this may be more appropriate as an assert?

**Comment by smaillet-ms** [comment]
This will require some detailed review. The reason for the verify here and the fact that it is the "AsString() method instead of TosString() overload is due to the fact that the underlying Native LLVM Apis have a tendency to trigger asserts and access violations on invalid bitcode. Thus the verification was used to catch such a case.
