### ISSUE TITLE
Add formal interop support for portability layer

### ISSUE THREAD

**Issue by lt72** [NETMF/llilum#8]
Besides all native types, we will need to support callbacks and most likely Strings

**Comment by ckarenz** [comment]
I think we now have support for all types here:
- Native types (Int32, bool, etc.) are supported.
- With the recent object layout changes, objects (both value and ref types) appear in C as they do in C#.
- Strings can be cast to char\* and passed directly to C functions.
- Callbacks are supported through delegate pointers.

Is there more work to do?

**Comment by smaillet-ms** [comment]
Strings aren't char\* compatible. char\* is 8bit ANSI/MBCS System.Char is Unicode-16. Are Llilum strings guaranteed to always be '\0' terminated (That's not the norm for .NET since the string type includes the length of the string the extra terminator is not required, however it is expected/required for most "C" APIs )

Other than that, I'd say the only thing remaining is to document, validate and provide samples on how to handle each case.

**Comment by ckarenz** [comment]
Discussed with Lorenzo.  Closing this as completed.  Conversions to single-byte char\* should be at the native level.
